version: "3.9"

services:
  backend:
    image: ${REGISTRY_HOST:-docker.io}/${REGISTRY_USER:-youruser}/flowboard-backend:${TAG:-latest}
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    networks: [appnet]
    restart: unless-stopped

  frontend:
    image: ${REGISTRY_HOST:-docker.io}/${REGISTRY_USER:-youruser}/flowboard-frontend:${TAG:-latest}
    depends_on: [backend]
    ports:
      - "8080:80"
    networks: [appnet]
    restart: unless-stopped

networks:
  appnet:
    driver: bridge
