version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-flowboard}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [appnet]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-cambialo}
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@db:5432/${POSTGRES_DB:-flowboard}
      CORS_ORIGIN: ${PUBLIC_FRONTEND_URL:-http://localhost}
      UPLOAD_DIR: /app/uploads
    depends_on: [db]
    volumes:
      # usa volumen nombrado o pon aquí una ruta absoluta del NAS
      - uploads_data:/app/uploads
    networks: [appnet]

  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_BASE: ${PUBLIC_API_URL:-/api}
    networks: [appnet]
    depends_on: [backend]

  nginx:
    image: nginx:1.25-alpine
    depends_on: [frontend, backend]
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [appnet]

volumes:
  pgdata:
  uploads_data:

networks:
  appnet:
    driver: bridge
